### ISSUE TITLE
this.infinityModel is not a function model

### ISSUE THREAD

**Issue by voodoologic** [ember-infinity/ember-infinity#245]
Following the readme, I got this error:
`this.infinityModel is not a function model`
I am using ember at version 2.16 so I assume it's because of the changes to import.  I noticed you are actively working on 1.0 so my question is this, how do I either fix or upgrade the plugin?
ember-inifnity worked great on a 2.12, but I am trying to keep my stack up to date. 

Fixes #247

**Comment by snewcomer** [comment]
@voodoologic 

1.  So in your `package.json`, you would just want to add `git+ssh://git@github.com/hhff/ember-infinity.git#1-0` for this lib.  There should be a big perf win coming in the next few weeks and upgrading to this branch most likely shouldn't bring you any issues.

2.  Did you mixin `import InfinityRoute from "ember-infinity/mixins/route";` this import to your route?

**Comment by voodoologic** [comment]
@snewcomer 
1. Awesome I'm going to try that now.

2. Yeah, I did that.  No luck.

**Comment by Duder-onomy** [comment]
@voodoologic I bet you need to clear your npm/yarn cache after upgrading to the 1-0 branch. 
`this.infinityModel` does not exist in the 1-0 branch.

**Comment by voodoologic** [comment]
@Duder-onomy `yarn cache clean` then `yarn`  still no luck.  I can try against a clean build for a sanity check.  Nice name, btw.

**Comment by snewcomer** [comment]
@voodoologic mind pasting the relevant route code here?

**Comment by voodoologic** [comment]
```
import Route from '@ember/routing/route';
import {
  InfinityRoute,
  InfinityModel
}from "ember-infinity/mixins/route"

export default Route.extend({
  // model() {
  //   this.store.findAll('tweet')
  // }
  model(params) {
    if ((params.hashtag != null ) && (params.user != null)) {
      return this.infinityModel('tweet', {
        perPage: 50,
        startingPage: 1,
        hashtag: params.hashtag,
        user: params.user
      })
    } else if (params.hashtag != null ) {
      return this.infinityModel('tweet',{
        perPage: 50,
        startingPage: 1,
        hashtag: params.hashtag
      })
    } else if (params.user != null) {
      return this.infinityModel('tweet', {
        perPage: 50,
        startingPage: 1,
        user: params.user
      })
    } else {
      debugger
      return this.infinityModel('tweet', {
        perPage: 50,
        startingPage: 1,
      })
    }
  }
});
```

**Comment by snewcomer** [comment]
Ah so you need to mixin the infinity route you imported to your route then should be g2g.  ‘Route.extend(InfinityRoute, {‘

**Comment by voodoologic** [comment]
@snewcomer  Oh, of course! I've come across this snag before.  It's not entirely apparent from the readme that the line is different.  I'll craft a pull request addressing the doc so maybe it will help with adoption.  I'm excited to get coding again!  Also, even though the solution was simple, I'm happy to get the tip on 1-0 build. Cheers.
:beers: Happy New Years.
